In [1]:
import pandas as pd

In [2]:
db = pd.read_csv("E:\programs\python programs\ml basics\youtube_playlist1\minorP\link_data_final.csv",index_col=0)
db.head()

,label,result,IPpresent,url_len,dotC,dslashC,delimC,shady_tld,atC,https_present,primDom_len,path_len
url,,,,,,,,,,,,
https://www.google.com,benign,0,0,22,2,1,0,0,0,1,14,0
https://www.youtube.com,benign,0,0,23,2,1,0,0,0,1,15,0
https://www.facebook.com,benign,0,0,24,2,1,0,0,0,1,16,0
https://www.baidu.com,benign,0,0,21,2,1,0,0,0,1,13,0
https://www.wikipedia.org,benign,0,0,25,2,1,0,0,0,1,17,0

In [15]:
r,c= db.shape
print(r,c)

525819 10

In [10]:
label_dict = {0 : 1, 1 : 0}

db['IPpresent'] = db['IPpresent'].map(label_dict)

db.head()

,label,result,IPpresent,url_len,dotC,dslashC,sslashC,hyphenC,delimC,unsafeDelimC
url,,,,,,,,,,
https://www.google.com,benign,0,0,22,2,1,2,0,0,0
https://www.youtube.com,benign,0,0,23,2,1,2,0,0,0
https://www.facebook.com,benign,0,0,24,2,1,2,0,0,0
https://www.baidu.com,benign,0,0,21,2,1,2,0,0,0
https://www.wikipedia.org,benign,0,0,25,2,1,2,0,0,0

In [3]:
db.set_index("url", inplace = True)

In [4]:
db.to_csv('E:\programs\python programs\ml basics\youtube_playlist1\minorP\link_data_final.csv')

In [3]:
#for checking subdirectories
db['sslashC'] = db['url'].str.count('/')

In [24]:
db.tail()

,url,label,result,IPpresent,url_len,dotC,dslashC,sslashC,hyphenC,delimC,shady_tld
525814,23.227.196.215/,malicious,1,1,15,3,0,1,0,0,0
525815,apple-checker.org/,malicious,1,0,18,1,0,1,1,0,0
525816,apple-iclods.org/,malicious,1,0,17,1,0,1,1,0,0
525817,apple-uptoday.org/,malicious,1,0,18,1,0,1,1,0,0
525818,apple-search.info,malicious,1,0,17,1,0,0,1,0,0

In [4]:
db['sslashC'] = db['sslashC'] - (2*db['dslashC'])

In [5]:
db= db.drop(['unsafeDelimC'], axis=1)

In [18]:
shady_tld = ('.country','.kim','.science','.gq','.work','.ninja','.xyz','.date','.faith','.zip','.racing','.cricket','.win','.space','.accountant','.realtor','.top','.stream','.christmas','.gdn','.mom','.pro','.men','.review','.party','.link')

In [19]:
db['shady_tld'] = db['url'].str.endswith(shady_tld)

In [20]:
label_dict = {True : 1, False: 0}
db['shady_tld'] = db['shady_tld'].map(label_dict)

In [21]:
(db.groupby('shady_tld').size()/db['shady_tld'].count())*100

shady_tld
0    99.870678
1     0.129322
dtype: float64

In [5]:
db_shtld = db.groupby('shady_tld')
dbtld = db_shtld.get_group(1)

In [23]:
db_ben_shadytld=dbtld.groupby('label')
db_ben_shady = db_ben_shadytld.get_group('benign')
db_ben_shady

,url,label,result,IPpresent,url_len,dotC,dslashC,sslashC,hyphenC,delimC,shady_tld
503,https://www.oload.stream,benign,0,0,24,2,1,0,0,0,1
1682,https://www.bskn.pro,benign,0,0,20,2,1,0,0,0,1
1700,https://www.axdst.pro,benign,0,0,21,2,1,0,0,0,1
1886,https://www.buyandfun.win,benign,0,0,25,2,1,0,0,0,1
1971,https://www.huobi.pro,benign,0,0,21,2,1,0,0,0,1
2266,https://www.bneoc.pro,benign,0,0,21,2,1,0,0,0,1
2274,https://www.smrtlnk.pro,benign,0,0,23,2,1,0,0,0,1
184848,https://www.facebook.com/Mousers.mom,benign,0,0,36,3,1,1,0,0,1
207626,https://www.guardian.co.uk/science/2003/jul/03...,benign,0,0,63,4,1,5,0,0,1

In [3]:
db.describe()

,result,IPpresent,url_len,dotC,dslashC,sslashC,hyphenC,delimC,shady_tld
count,525819.000000,525819.000000,525819.000000,525819.000000,525819.000000,525819.000000,525819.000000,525819.000000,525819.000000
mean,0.342477,0.015321,59.405881,2.577345,0.862483,2.473003,1.139141,1.055270,0.001293
std,0.474539,0.122826,41.959954,1.286937,0.359184,1.606058,2.435030,3.079587,0.035938
min,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,38.000000,2.000000,1.000000,1.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,51.000000,2.000000,1.000000,2.000000,0.000000,0.000000,0.000000
75%,1.000000,0.000000,70.000000,3.000000,1.000000,3.000000,1.000000,1.000000,0.000000
max,1.000000,1.000000,2314.000000,32.000000,7.000000,42.000000,42.000000,205.000000,1.000000

In [18]:
db_label = db.groupby('label')
dbben = db_label.get_group('benign')
r3,c3= dbben.shape
print(r3,c3)

345738 10

In [1]:
525819-345738

180081

In [19]:
dbben.drop_duplicates(keep='first', inplace=True)
r1,c1= dbben.shape
print(r1,c1)

33697 10

C:\Users\Dell\Anaconda3\envs\mal_url\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [30]:
dbml = db_label.get_group('malicious')
dbml_ip = dbml.groupby('IPpresent')
dbml_ipa = dbml_ip.get_group(0)
r4,c4= dbml_ipa.shape
print(r4,c4)

172025 10

In [33]:
dbml_ipa.drop_duplicates(keep='first', inplace=True)
r5,c5= dbml_ipa.shape
print(r5,c5)

37785 10

C:\Users\Dell\Anaconda3\envs\mal_url\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [34]:
dbml_ipp = dbml_ip.get_group(1)
db_new = pd.concat([dbben, dbml_ipa,dbml_ipp], axis = 0)
r6,c6 = db_new.shape
print(r6,c6)
db_new.head()

79538 10

,label,result,IPpresent,url_len,dotC,dslashC,sslashC,hyphenC,delimC,shady_tld
url,,,,,,,,,,
https://www.google.com,benign,0,0,22,2,1,0,0,0,0
https://www.youtube.com,benign,0,0,23,2,1,0,0,0,0
https://www.facebook.com,benign,0,0,24,2,1,0,0,0,0
https://www.baidu.com,benign,0,0,21,2,1,0,0,0,0
https://www.wikipedia.org,benign,0,0,25,2,1,0,0,0,0

In [36]:
db_new.tail(10)

,label,result,IPpresent,url_len,dotC,dslashC,sslashC,hyphenC,delimC,shady_tld
url,,,,,,,,,,
46.17.97.37/Servermac.php,malicious,1,1,25,4,0,1,0,0,0
5.200.52.198/flex/3435dde3r.exe,malicious,1,1,31,4,0,2,0,0,0
195.22.127.233/rec/fre.php,malicious,1,1,26,4,0,2,0,0,0
195.22.127.233:80/rec/fre.php,malicious,1,1,29,4,0,2,0,0,0
146.71.84.110,malicious,1,1,13,3,0,0,0,0,0
185.175.208.12,malicious,1,1,14,3,0,0,0,0,0
94.140.120.88,malicious,1,1,13,3,0,0,0,0,0
185.163.46.150/software.exe,malicious,1,1,27,4,0,1,0,0,0
60.250.76.52/,malicious,1,1,13,3,0,1,0,0,0
23.227.196.215/,malicious,1,1,15,3,0,1,0,0,0

In [38]:
db_new.to_csv('E:\programs\python programs\ml basics\youtube_playlist1\minorP\short_urldata.csv')

In [39]:
(db_new.groupby('label').size()/db_new['label'].count())*100

label
benign       42.365913
malicious    57.634087
dtype: float64

In [1]:
import pandas as pd
import sklearn
from sklearn import svm, preprocessing

In [2]:
db_new= pd.read_csv("E:\programs\python programs\ml basics\youtube_playlist1\minorP\link_data_final.csv")
db_new.head()

,url,label,result,IPpresent,url_len,dotC,dslashC,delimC,shady_tld,atC,https_present,primDom_len,path_len
0,https://www.google.com,benign,0,0,22,2,1,0,0,0,1,14,0
1,https://www.youtube.com,benign,0,0,23,2,1,0,0,0,1,15,0
2,https://www.facebook.com,benign,0,0,24,2,1,0,0,0,1,16,0
3,https://www.baidu.com,benign,0,0,21,2,1,0,0,0,1,13,0
4,https://www.wikipedia.org,benign,0,0,25,2,1,0,0,0,1,17,0

In [5]:
db_new = sklearn.utils.shuffle(db_new)
db_new.head()

,label,result,IPpresent,url_len,dotC,dslashC,delimC,shady_tld,atC,https_present,primDom_len,path_len
url,,,,,,,,,,,,
https://www.silverspringmd.lionwap.org/,benign,0,0,39,3,1,1,0,0,1,30,1
https://www.wsn.com/football/uefa-champions-league-odds/,benign,0,0,56,2,1,6,0,0,1,11,37
https://www.manufacturedirections.net/washington/orting/1019774-laura-barrentine.html,benign,0,0,85,3,1,5,0,0,1,29,48
http://cloudrepublic.com.au/7g6bubt7v,malicious,1,0,37,2,1,1,0,0,0,20,10
https://www.emerson.edu/academics/departments/writing-literature-publishing/faculty?facultyID=2513&filter=F,benign,0,0,107,2,1,10,0,0,1,15,60

In [9]:
import numpy as np
from sklearn.model_selection import cross_validate
X = np.array(db_new.drop(['label','result'],1))
y = np.array(db_new['result'])

X_train, X_test, y_train,y_test = sklearn.model_selection.train_test_split(X,y,test_size=0.2)
X

array([[ 0, 39,  3, ...,  1, 30,  1],
       [ 0, 56,  2, ...,  1, 11, 37],
       [ 0, 85,  3, ...,  1, 29, 48],
       ...,
       [ 0, 51,  1, ...,  0, 10, 34],
       [ 0, 55,  3, ...,  1, 20, 27],
       [ 0, 43,  2, ...,  1, 15,  6]], dtype=int64)

In [7]:
from sklearn import neighbors

In [10]:
clf= neighbors.KNeighborsClassifier()

clf.fit(X_train, y_train)

accuracy = clf.score(X_test, y_test)
print('Model accuracy = ', accuracy*100)

Model accuracy =  97.19295576433001

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
clf= LogisticRegression()
clf.fit(X_train, y_train)

accuracy = clf.score(X_test, y_test)
print('Model accuracy = ', accuracy*100)

C:\Users\Dell\Anaconda3\envs\mal_url\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

Model accuracy =  98.79806777984862