In [3]:
import numpy as np
import pandas as pd

In [86]:
db = pd.read_csv("E:\programs\python programs\ml basics\youtube_playlist1\minorP\link_data_final.csv")
db.head()

,url,label,result,IPpresent,url_len,dotC,dslashC,delimC,shady_tld,atC,https_present,primDom_len,path_len
0,https://www.google.com,benign,0,0,22,2,1,0,0,0,1,14,0
1,https://www.youtube.com,benign,0,0,23,2,1,0,0,0,1,15,0
2,https://www.facebook.com,benign,0,0,24,2,1,0,0,0,1,16,0
3,https://www.baidu.com,benign,0,0,21,2,1,0,0,0,1,13,0
4,https://www.wikipedia.org,benign,0,0,25,2,1,0,0,0,1,17,0

In [3]:
(db.groupby('label').size()/db['label'].count())*100

label
benign       65.752284
malicious    34.247716
dtype: float64

In [140]:
db['IPpresent'] = db['url'].str.match('^(http://|https://||ftp://)\d+\.\d+\.\d+\.\d+\.*')

In [141]:
print(db['IPpresent'].unique())

[False  True]

In [142]:
db_ip = db.groupby('IPpresent')

In [143]:
(db.groupby('IPpresent').size()/db['IPpresent'].count())*100

IPpresent
False    98.467914
True      1.532086
dtype: float64

In [144]:
db_isIP = db_ip.get_group(True)
db_isIP.head()

,url,label,result,IPpresent
345994,http://93.186.251.133/exchange/signup/login.php,malicious,4,True
346012,http://37.60.238.238/~skylins3/,malicious,4,True
346052,http://80.211.171.247/foxbit.exchange/%23signin/,malicious,4,True
346144,http://80.211.156.45,malicious,4,True
346650,http://000.9.009.09.ekurbani.com/faldtwo.htm,malicious,4,True

In [137]:
db_isIP.tail()

                                url      label  result  IPpresent
525752               185.175.208.12  malicious       4       True
525753                94.140.120.88  malicious       4       True
525755  185.163.46.150/software.exe  malicious       4       True
525797                60.250.76.52/  malicious       4       True
525814              23.227.196.215/  malicious       4       True

In [145]:
db.head()

                         url   label  result  IPpresent
0     https://www.google.com  benign       2      False
1    https://www.youtube.com  benign       2      False
2   https://www.facebook.com  benign       2      False
3      https://www.baidu.com  benign       2      False
4  https://www.wikipedia.org  benign       2      False

In [146]:
label_dict2 = {True : 0, False : 1}

db['IPpresent'] = db['IPpresent'].map(label_dict2)

db.head()

                         url   label  result  IPpresent
0     https://www.google.com  benign       2          1
1    https://www.youtube.com  benign       2          1
2   https://www.facebook.com  benign       2          1
3      https://www.baidu.com  benign       2          1
4  https://www.wikipedia.org  benign       2          1

In [71]:
db['url_len'] = db['url'].str.len()

In [197]:
db.tail(10)

,url,label,result,IPpresent,url_len,dotC,dslashC,atC,sslashC,hyphenC,delimC,semicolC,underscoreC,quesC,equalC,andC
525809,defibel.org/wp-includes/images/index.html,malicious,4,1,41,2,0,0,3,1,0,0,0,0,0,0
525810,shapingsoftware.com/2009/02/09/architectural-s...,malicious,4,1,52,1,0,0,5,1,0,0,0,0,0,0
525811,free.ulohapp.info/?br_fl=2872&amp;tuif=5539&am...,malicious,4,1,279,6,0,0,1,0,28,6,8,1,7,6
525812,free.ulohapp.info/?oq=CEh3h_PskJLFZaQWwjEKBegU...,malicious,4,1,280,6,0,0,1,2,28,6,8,1,7,6
525813,mol.com-ho.me/cv_itworx.doc,malicious,4,1,27,3,0,0,1,1,1,0,1,0,0,0
525814,23.227.196.215/,malicious,4,0,15,3,0,0,1,0,0,0,0,0,0,0
525815,apple-checker.org/,malicious,4,1,18,1,0,0,1,1,0,0,0,0,0,0
525816,apple-iclods.org/,malicious,4,1,17,1,0,0,1,1,0,0,0,0,0,0
525817,apple-uptoday.org/,malicious,4,1,18,1,0,0,1,1,0,0,0,0,0,0
525818,apple-search.info,malicious,4,1,17,1,0,0,0,1,0,0,0,0,0,0

In [186]:
db['dotC'] = db['url'].str.count('\.')

In [73]:
#for checking redirection
db['dslashC'] = db['url'].str.count('//')

In [7]:
db['atC'] = db['url'].str.count('@')

In [176]:
#for checking subdirectories
db['sslashC'] = db['url'].str.count('/')

In [178]:
db['hyphenC'] = db['url'].str.count('-')

In [192]:
#delimiters count
#delim_list = [';','_','?','=','&']
db['semicolC'] = db['url'].str.count(';')
db['underscoreC'] = db['url'].str.count('_')
db['quesC'] = db['url'].str.count('\?')
db['equalC'] = db['url'].str.count('=')
db['andC'] = db['url'].str.count('&')

In [196]:
delim_col = ['semicolC', 'underscoreC', 'quesC', 'equalC', 'andC']
db['delimC'] = db[delim_col].sum(axis=1)

In [198]:
db.drop(['semicolC', 'underscoreC', 'quesC', 'equalC', 'andC'],axis=1)

,url,label,result,IPpresent,url_len,dotC,dslashC,atC,sslashC,hyphenC,delimC
0,https://www.google.com,benign,2,1,22,2,1,0,2,0,0
1,https://www.youtube.com,benign,2,1,23,2,1,0,2,0,0
2,https://www.facebook.com,benign,2,1,24,2,1,0,2,0,0
3,https://www.baidu.com,benign,2,1,21,2,1,0,2,0,0
4,https://www.wikipedia.org,benign,2,1,25,2,1,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...
525814,23.227.196.215/,malicious,4,0,15,3,0,0,1,0,0
525815,apple-checker.org/,malicious,4,1,18,1,0,0,1,1,0
525816,apple-iclods.org/,malicious,4,1,17,1,0,0,1,1,0
525817,apple-uptoday.org/,malicious,4,1,18,1,0,0,1,1,0
525818,apple-search.info,malicious,4,1,17,1,0,0,0,1,0

In [203]:
db.to_csv('E:\programs\python programs\ml basics\youtube_playlist1\minorP\link_data_final.csv')

In [201]:
db.set_index("url", inplace = True)

In [202]:
db.head()

,label,result,IPpresent,url_len,dotC,dslashC,atC,sslashC,hyphenC,delimC,semicolC,underscoreC,quesC,equalC,andC
url,,,,,,,,,,,,,,,
https://www.google.com,benign,2,1,22,2,1,0,2,0,0,0,0,0,0,0
https://www.youtube.com,benign,2,1,23,2,1,0,2,0,0,0,0,0,0,0
https://www.facebook.com,benign,2,1,24,2,1,0,2,0,0,0,0,0,0,0
https://www.baidu.com,benign,2,1,21,2,1,0,2,0,0,0,0,0,0,0
https://www.wikipedia.org,benign,2,1,25,2,1,0,2,0,0,0,0,0,0,0

In [1]:
import pandas as pd
import matplotlib

In [2]:
db = pd.read_csv("E:\programs\python programs\ml basics\youtube_playlist1\minorP\link_data_final.csv", index_col=0)
db.head()

,Unnamed: 0,label,result,IPpresent,url_len,dotC,dslashC,sslashC,hyphenC,delimC,unsafeDelimC
url,,,,,,,,,,,
https://www.google.com,0,benign,2,1,22,2,1,2,0,0,0
https://www.youtube.com,1,benign,2,1,23,2,1,2,0,0,0
https://www.facebook.com,2,benign,2,1,24,2,1,2,0,0,0
https://www.baidu.com,3,benign,2,1,21,2,1,2,0,0,0
https://www.wikipedia.org,4,benign,2,1,25,2,1,2,0,0,0

In [25]:
db.tail()

,url,label,result,IPpresent,url_len,dotC,dslashC,sslashC,hyphenC,delimC,unsafeDelimC
525814,23.227.196.215/,malicious,4,0,15,3,0,1,0,0,0
525815,apple-checker.org/,malicious,4,1,18,1,0,1,1,0,0
525816,apple-iclods.org/,malicious,4,1,17,1,0,1,1,0,0
525817,apple-uptoday.org/,malicious,4,1,18,1,0,1,1,0,0
525818,apple-search.info,malicious,4,1,17,1,0,0,1,0,0

In [4]:
db = db.drop(['semicolC', 'underscoreC', 'quesC', 'equalC', 'andC'],axis=1)

In [9]:
delim_l = ['delimC','atC']
db['delimC'] = db[delim_l].sum(axis=1)
db= db.drop(['atC'], axis=1)

In [21]:
#unsafe delimiters
#unsafe_delim = ['<','>','#','^','~']
db['us<C'] = db['url'].str.count('<')
db['us>C'] = db['url'].str.count('>')
db['us#C'] = db['url'].str.count('#')
db['us%C'] = db['url'].str.count('%')#not to be used
db['us^C'] = db['url'].str.count('\^')
db['us~C'] = db['url'].str.count('~')

In [24]:
unsafe_delim = ['us<C','us>C','us#C','us%C','us^C','us~C']
db['unsafeDelimC'] = db[unsafe_delim].sum(axis=1)
db= db.drop(['us<C','us>C','us#C','us%C','us^C','us~C'], axis=1)

In [83]:
db.to_csv('E:\programs\python programs\ml basics\youtube_playlist1\minorP\link_data_final.csv')

In [28]:
db['us%C'] = db['url'].str.count('%')

In [29]:
db['unsafeDelimC'] = db['unsafeDelimC'] - db['us%C']

In [82]:
db.set_index("url", inplace = True)

In [33]:
db.head()

,label,result,IPpresent,url_len,dotC,dslashC,sslashC,hyphenC,delimC,unsafeDelimC
url,,,,,,,,,,
https://www.google.com,benign,2,1,22,2,1,2,0,0,0
https://www.youtube.com,benign,2,1,23,2,1,2,0,0,0
https://www.facebook.com,benign,2,1,24,2,1,2,0,0,0
https://www.baidu.com,benign,2,1,21,2,1,2,0,0,0
https://www.wikipedia.org,benign,2,1,25,2,1,2,0,0,0

In [32]:
db= db.drop(['us%C'], axis=1)

In [10]:
#unsafeList2 = ['[',']','|','{','}']
db['us[C'] = db['url'].str.count('\[')
db['us]C'] = db['url'].str.count('\]')
db['us|C'] = db['url'].str.count('\|')
db['us{C'] = db['url'].str.count('\{')
db['us}C'] = db['url'].str.count('}')

In [3]:
db = pd.read_csv("E:\programs\python programs\ml basics\youtube_playlist1\minorP\link_data_final.csv")
db.head()

,url,label,result,IPpresent,url_len,dotC,dslashC,sslashC,hyphenC,delimC,unsafeDelimC
0,https://www.google.com,benign,2,1,22,2,1,2,0,0,0
1,https://www.youtube.com,benign,2,1,23,2,1,2,0,0,0
2,https://www.facebook.com,benign,2,1,24,2,1,2,0,0,0
3,https://www.baidu.com,benign,2,1,21,2,1,2,0,0,0
4,https://www.wikipedia.org,benign,2,1,25,2,1,2,0,0,0

In [5]:
db.tail()

,label,result,IPpresent,url_len,dotC,dslashC,sslashC,hyphenC,delimC,unsafeDelimC
url,,,,,,,,,,
23.227.196.215/,malicious,4,0,15,3,0,1,0,0,0
apple-checker.org/,malicious,4,1,18,1,0,1,1,0,0
apple-iclods.org/,malicious,4,1,17,1,0,1,1,0,0
apple-uptoday.org/,malicious,4,1,18,1,0,1,1,0,0
apple-search.info,malicious,4,1,17,1,0,0,1,0,0

In [13]:
unsafe_delim2 = ['us[C','us]C','us{C','us}C','us|C','unsafeDelimC']
db['unsafeDelimC'] = db[unsafe_delim2].sum(axis=1)
db= db.drop(['us[C','us]C','us{C','us}C','us|C','us\C'], axis=1)

In [4]:
db= db.drop(['Unnamed: 0'], axis=1)

# paper features

In [81]:
db.head(10)

,url,label,result,IPpresent,url_len,dotC,dslashC,delimC,shady_tld,atC,https_present,primDom_len,path_len
0,https://www.google.com,benign,0,0,22,2,1,0,0,0,1,14,0
1,https://www.youtube.com,benign,0,0,23,2,1,0,0,0,1,15,0
2,https://www.facebook.com,benign,0,0,24,2,1,0,0,0,1,16,0
3,https://www.baidu.com,benign,0,0,21,2,1,0,0,0,1,13,0
4,https://www.wikipedia.org,benign,0,0,25,2,1,0,0,0,1,17,0
5,https://www.reddit.com,benign,0,0,22,2,1,0,0,0,1,14,0
6,https://www.yahoo.com,benign,0,0,21,2,1,0,0,0,1,13,0
7,https://www.google.co.in,benign,0,0,24,3,1,0,0,0,1,16,0
8,https://www.qq.com,benign,0,0,18,2,1,0,0,0,1,10,0
9,https://www.amazon.com,benign,0,0,22,2,1,0,0,0,1,14,0

In [8]:
db['delimC']= db['delimC']-db['atC']

In [9]:
li=['delimC', 'hyphenC']
db['delimC'] = db[li].sum(axis=1)

In [10]:
db= db.drop(['hyphenC'], axis=1)

In [11]:
li=['delimC', 'sslashC']
db['delimC'] = db[li].sum(axis=1)

In [12]:
db= db.drop(['sslashC'], axis=1)

In [17]:
from urllib.parse import urlparse

In [60]:
def https_pr(url):
    urldis = urlparse(url)
    if urldis.scheme == 'https':
        return 1
    else :
        return 0

In [61]:
db['https_present']= db['url'].apply(https_pr)

In [77]:
o = urlparse('http://mol.com-ho.me/cv_itworx.doc')
o

ParseResult(scheme='http', netloc='mol.com-ho.me', path='/cv_itworx.doc', params='', query='', fragment='')

In [64]:
def httpadd(url):
    urldis = urlparse(url)
    if urldis.scheme == '':
        return ('http://' + url)
    else:
        return url
    
db['url'] = db['url'].apply(httpadd)

In [67]:
def pridomlen(url):
    urldis = urlparse(url)
    return len(urldis.netloc)

In [68]:
db['primDom_len']= db['url'].apply(pridomlen)

In [78]:
def pathlen(url):
    urldis = urlparse(url)
    return len(urldis.path)

In [79]:
db['path_len'] = db['url'].apply(pathlen)

In [84]:
def port_pr(url):
    urldis = urlparse(url)
    if isinstance(urldis.port,int):
        return 1
    else:
        return 0